### ISSUE TITLE
Problems with grpc-server-spring-boot-starter

### ISSUE THREAD

**Issue by masalinas** [tdilber/grpc-swagger-springdoc-openapi#1]
Using the **grpc-server-spring-boot-starter** version **2.14.0.RELEASE** to start the gRPC Server not start with **Springboot 3**, so you must to use **Springboot 2**, but then **springdoc-openapi v2.0.0** not works, so how resolve this inconsistency?

**Comment by masalinas** [comment]
Finally I started the gRPC server using Springboot 3 following the [#775](https://github.com/yidongnan/grpc-spring-boot-starter/pull/775) trick

**Comment by tdilber** [comment]
I also faced same problem then i use this method : 
@ImportAutoConfiguration({GrpcClientAutoConfiguration.class, GrpcServerAutoConfiguration.class, GrpcServerFactoryAutoConfiguration.class})

U can see in this link: https://github.com/tdilber/anouncy/blob/master/backend/location/src/main/java/com/beyt/anouncy/location/LocationApplication.java
